import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import localFont from "next/font/local";
import { ThemeProvider as NextThemesProvider } from "next-themes";
import AuthSessionProvider from "@/context/SessionProvider";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";
import { UserProvider } from "@/context/UserProvider";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Work-HQ",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  // console.log(session);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <Provider store={store}> */}
        <AuthSessionProvider session={session}>
          <NextThemesProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
          >
            <UserProvider>
            {children}
            </UserProvider>
            <Toaster />
          </NextThemesProvider>
        </AuthSessionProvider>
        {/* </Provider> */}
      </body>
    </html>
  );
}
